site_name: NSI première
theme:
  name: material
  language: fr
  favicon: img/favicon.png
  palette:
    primary: black
    scheme : slate
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 'Partie 1':
    - 'C1 : Python les base':
      - 'Cours': 'c1c.md'
      - 'Activité' : 'c1a.md'
      - 'Révision' : 'c1r.md'
    - 'C2 : Les séquences':
      - 'Cours': 'c2c.md'
      - 'Activité' : 'c2a.md'
      - 'Révision' : 'c2r.md'
    - 'C3 : Les dictionnaires':
      - 'Cours': 'c3c.md'
      - 'Activité' : 'c3a.md'
      - 'Révision' : 'c3r.md'
  - "Projet 1" : 'pr1.md'
  - 'Partie 2':
    - "C4 : entier positif":
      - 'Cours': 'c4c.md'
      - 'Activité' : 'c4a.md'
      - 'Révision' : 'c4r.md'
    - "C5 : texte":
      - 'Cours': 'c5c.md'
      - 'Activité' : 'c5a.md'
      - 'Révision' : 'c5r.md'
    - "C6 : entier relatif":
      - 'Cours': 'c6c.md'
      - 'Activité' : 'c6a.md'
      - 'Révision' : 'c6r.md'
    - "C7 : nombre flottant":
      - 'Cours': 'c7c.md'
      - 'Activité' : 'c7a.md'
      - 'Révision' : 'c7r.md'
  - 'Partie 3':
    - "C8 : archi de von Neumann":
      - 'Cours': 'c8c.md'
      - 'Activité' : 'c8a.md'
      - 'Révision' : 'c8r.md'
    - 'C9 : simulation CPU':
      - 'Activité' : 'c9a.md'
  - "Projet 2" : 'pr2.md'
  - 'Partie 4':
    - "C10 : intro à l'algorithmique":
      - 'Cours': 'c10c.md'
      - 'Activité' : 'c10a.md'
      - 'Révision' : 'c10r.md'
    - 'C11 : tri par insertion et sélection':
      - 'Cours': 'c11c.md'
      - 'Activité' : 'c11a.md'
      - 'Révision' : 'c11r.md'
    - 'C12 : invariants de boucle':
      - 'Cours': 'c12c.md'
      - 'Activité' : 'c12a.md'
      - 'Révision' : 'c12r.md'
  - 'Partie 5':
    - "C13 : Systèmes d'exploitation" :
      - 'Cours': 'c13c.md'
      - 'Activité' : 'c13a.md'
      - 'Révision' : 'c13r.md'
    - 'C14 : Commandes Linux':
      - 'Cours': 'c14c.md'
      - 'Activité' : 'c14a.md'
      - 'Révision' : 'c14r.md'
    - 'C15 : langages de programmation':
      - 'Cours': 'c15c.md'
      - 'Activité' : 'c15a.md'
      - 'Révision' : 'c15r.md'
  - "Projet 3" : 'pr3.md'
  - 'Partie 6':
    - "C16 : introduction réseau" :
      - 'Cours': 'c16c.md'
      - 'Activité' : 'c16a.md'
      - 'Révision' : 'c16r.md'
    - "C17 : TCP et IP" :
      - 'Cours': 'c17c.md'
      - 'Activité' : 'c17a.md'
      - 'Révision' : 'c17r.md'
    - "C18 : Modèle TCP/IP" :
      - 'Cours': 'c18c.md'
      - 'Activité' : 'c18a.md'
      - 'Révision' : 'c18r.md'
    - 'C19 : simulation réseau (I)':
      - 'Activité' : 'c19a.md'
    - 'C20 : bit alterné':
      - 'Cours': 'c20c.md'
      - 'Activité' : 'c20a.md'
      - 'Révision' : 'c20r.md'
  - 'Partie 7':
    - "C21 : recherche dichotomique" :
      - 'Cours': 'c30c.md'
      - 'Activité' : 'c30a.md'
      - 'Révision' : 'c30r.md'
    - "C22 : algo gloutons" :
      - 'Cours': 'c31c.md'
      - 'Activité' : 'c31a.md'
      - 'Révision' : 'c31r.md'
    - "C23 : algo des k plus proches voisins" :
      - 'Cours': 'c32c.md'
      - 'Activité' : 'c32a.md'
      - 'Révision' : 'c32r.md'
  - "Projet 4" : 'pr5.md'
  - 'Partie 8':
    - "C24 : introduction au web" :
      - 'Cours': 'c21c.md'
      - 'Activité' : 'c21a.md'
      - 'Révision' : 'c21r.md'
    - "C25 : les URL" :
      - 'Cours': 'c22c.md'
      - 'Activité' : 'c22a.md'
      - 'Révision' : 'c22r.md'
    - "C26 : HTML et CSS" :
      - 'Cours': 'c23c.md'
      - 'Activité' : 'c23a.md'
      - 'Révision' : 'c23r.md'
    - "C27 : interaction avec l'utilisateur" :
      - 'Cours': 'c24c.md'
      - 'Activité' : 'c24a.md'
      - 'Révision' : 'c24r.md'
    - 'C28 : modèle client/serveur':
      - 'Cours': 'c25c.md'
      - 'Activité' : 'c25a.md'
      - 'Révision' : 'c25r.md'
    - "C29 : protocole HTTP" :
      - 'Cours': 'c26c.md'
      - 'Activité' : 'c26a.md'
      - 'Révision' : 'c26r.md'
    - "C30 : simulation réseau (II)" :
      - 'Activité' : 'c27a.md'
    - "C31 : formulaire d'une page web":
      - 'Activité' : 'c28a.md'
  - "Projet 5" : 'pr4.md'
  - 'Partie 9':
    - "C32 : Données en tables" :
      - 'Cours': 'c29c.md'
      - 'Activité' : 'c29a.md'
      - 'Révision' : 'c29r.md'
  - 'Partie 10':
    - "C33: interface Homme - Machine" :
      - 'Cours': 'c33c.md'
  


